### ISSUE TITLE
Waveshare 2.9" V4 example on ESP32-C6: compilation issues and wrong 3-day forecast

### ISSUE THREAD

**Issue by oleshkamoraru** [G6EJD/ESP32-e-Paper-Weather-Display#287]
Hi everyone,
I’m working with a Waveshare 2.9 V4 example on an ESP32-C6. At first, I got several compilation errors, and I realized I had to manually add the missing header files (such as common.h, lang.h, etc.) into the same folder. After fixing that, I started getting compilation errors related to this struct:

```
typedef struct {   // For current Day and Day 1, 2, 3, etc.
  String Time;
  float  High;
  float  Low;
} HL_record_type;
```

To get the code to compile, I commented out this part inside the .ino file, because the struct was also being referenced in common.h.
My question is: was this the correct approach, or should I have commented it out only inside common.h instead?

I had a similar issue with these declarations:

```
Forecast_record_type  WxConditions[1];
Forecast_record_type  WxForecast[max_readings];
```

So I ended up commenting those out in the .ino file as well.

My display is a WeAct Studio 2.9" RWB model, so I adapted the code to make it work with this version. Right now almost everything works, except the “next 3-day forecast” section: all 3 days are displayed as the same day, and all temperatures are shown as 0°C, even though the weather icons (clouds/rain) update correctly.

Could someone help me understand where the error might be coming from?
Thank you!
I’m attaching a photo of the output.

![Image](https://github.com/user-attachments/assets/37604901-3ff4-4392-9251-a3eb6cf12187)

**Comment by oleshkamoraru** [comment]
here are the next 3 days in serial print

Data for DAY - 1 --------------
11:00 22/11/25
Summary: Expect a day of partly cloudy with snow
Temp   : 2.80
High   : 3.53
Low    : -1.94
Humi   : 79.00
PoP    : 100%
UVI    : 1.0
Rain   : 0.00
Snow   : 4.79
Icon   : 13d

Data for DAY - 2 --------------
11:00 23/11/25
Summary: There will be clear sky until morning, then partly cloudy
Temp   : 2.80
High   : 2.80
Low    : -2.02
Humi   : 79.00
PoP    : 14%
UVI    : 1.3
Rain   : 0.00
Snow   : 0.00
Icon   : 04d

Data for DAY - 3 --------------
11:00 24/11/25
Summary: Expect a day of partly cloudy with rain
Temp   : 0.44
High   : 1.30
Low    : 0.38
Humi   : 97.00
PoP    : 99%
UVI    : 0.2
Rain   : 2.31
Snow   : 0.00

**Comment by G6EJD** [comment]
I haven't got round to changing all the source code. The data displayed on the serial port is from the Daily array not the Forecast, this changed for the v3.0 API. So find the 3-day forecast display section and change the array name according. You can check common.h to see what it's displaying.

**Comment by G6EJD** [comment]
Change WwxForecast[ to Daily[ in the 3-day section
